### ISSUE TITLE
dashboard hangs, not displaying any info

### ISSUE THREAD

**Issue by jpvds** [IBM-Bluemix/insurance-bot-dashboard#39]
Going through the deme script, I ended up opening my (prod) dashboard app, it displays the "loading" circle, not displaying any info. "ALL CHATS (0)" although I have a chat open with Ana.

**Comment by l2fprod** [comment]
@jpvds 

I fixed an issue 2 days ago that was likely causing this. Something changed in Compose for MongoDB and it was not correctly handled. https://github.com/IBM-Bluemix/insurance-bot/commit/8b7b2f1842029062f38931190a64c212225afc8b.

You should recreate your toolchain with the latest Cloud Insurance code.

Please reopen if this does not solve the issue.
