### ISSUE TITLE
Dashboard App does not deploy

### ISSUE THREAD

**Issue by dscherme** [IBM-Bluemix/insurance-bot-dashboard#45]
I followed the directions in the demo script and could not get the dashboard app to deploy. The other 3 apps deploy correctly.

On the Bluemix dashboard under the Runtime tab it says there is no runtime. There are connections to Mongo and the Tone Analyzer service.

When I go into the Toolchain for the dashboard I see that the Deploy stage failed. The Build stage passed. I have included the log for the failed deploy stage.

Can someone help me get the Dashboard to deploy?

[Deploy Log for Dashboard.txt](https://github.com/IBM-Bluemix/insurance-bot-dashboard/files/704471/Deploy.Log.for.Dashboard.txt)

**Comment by l2fprod** [comment]
do you mind retrying from scratch? I just pushed several changes this morning in master (mainly migrating from Mongo to Cloudant, reduce the memory requirements and several bug fixes).

**Comment by l2fprod** [comment]
looks like this was using the codebase before the fix for Diego (VCAP_APP_PORT -> PORT). works with the most recent code. closing.
