### ISSUE TITLE
Running "npm run deploy:prod" fails on a mac

### ISSUE THREAD

**Issue by hlarubi** [IBM-Bluemix/insurance-bot-dashboard#50]
Hi,

I'm trying to follow the stand-alone steps to get this app deployed into a dedicated Bluemix environment that doesn't have the tool chain service provisioned. I see the following error trying to run "npm run deploy:prod". It seems that babel has been deprecated in favor of cli. Could you please help update the scripts to support this?

Thanks!

running better-npm-run in <mydir> bot-dashboard
Executing script: compile

to be executed: babel-node bin/compile 
/CSG-Bluemix-bot/bot-dashboard/bin/compile.js:1
(function (exports, require, module, __filename, __dirname) { import fs from 'fs-extra';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at loader (/CSG-Bluemix-bot/bot-dashboard/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/CSG-Bluemix-bot/bot-dashboard/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at Object.<anonymous> (/CSG-Bluemix-bot/bot-dashboard/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by l2fprod** [comment]
@hlarubi 

can you check your node and npm versions?

Mine are:
node v6.9.1
npm 3.10.8

I'm on a mac too and `npm install` + `npm run deploy:prod` work.

**Comment by hlarubi** [comment]
I just picked up the latest and greatest I could find and still the same issue...

With_SSL alexrubin$ node -v
v7.8.0
With_SSL alexrubin$ npm -v
4.4.4

**Comment by l2fprod** [comment]
I can not reproduce the issue :(

I did not have 7.8. So I did `nvm install 7.8` to get it, then `npm install -g npm` to get the latest.

```
$ ~/dev/cloudco/insurance-bot-dashboard> node -v
v7.8.0
$ ~/dev/cloudco/insurance-bot-dashboard> npm -v
4.4.4
```

and then

```
$ ~/dev/cloudco/insurance-bot-dashboard> rm -rf node_modules
$ ~/dev/cloudco/insurance-bot-dashboard> npm install
$ ~/dev/cloudco/insurance-bot-dashboard> npm run deploy:prod
...
  app:build:webpack-compiler No errors or warnings encountered. +77ms
  app:bin:compile Copy static assets to dist folder.
```

**Comment by hlarubi** [comment]
Thanks! What else should I be checking? Do I need to install babel to get this to work?

http://stackoverflow.com/questions/37634198/node-error-syntaxerror-unexpected-token-import
http://stackoverflow.com/questions/33604470/unexpected-token-import-in-nodejs5-and-babel

**Comment by l2fprod** [comment]
@hlarubi 

Could it be that another babel-node version exists in your path? or installed with npm -g? Try "babel-node -V" on the command line outside of the dashboard folder.

I don't have babel-node installed globally. When I build the project, it uses babel-node from ./node_modules/.bin. (coming with the babel-cli).

**Comment by hlarubi** [comment]
Thanks! Sorry, no luck:
$ which babel-node
$ babel-node -V
-bash: babel-node: command not found
$ ./node_modules/.bin/babel-node -V
6.24.1

Tried to add ./node_modules/.bin to all the babel-node calls in package.json, but no luck either...

Thanks!

**Comment by l2fprod** [comment]
@hlarubi this could be linked to conflicting packages or node versions.

Could you try to install nvm https://github.com/creationix/nvm#install-script ?

Once installed, do `nvm install 6.9.1` then the `npm install` and `npm run deploy:prod`.

nvm will ensure node versions are properly isolated from each other.

**Comment by hlarubi** [comment]
Thanks! I tried that and it works now! Much appreciated!

If you don't mind updating the directions that would help other folks that might run into the same issue. :-)

**Comment by l2fprod** [comment]
will put a generic recommendation. although this applies to any node.js projet and it is more a "node.js developer reco" than anything specific to these projects.

https://github.com/IBM-Bluemix/insurance-bot/issues/181
