### ISSUE TITLE
Dashboard does not run anymore.

### ISSUE THREAD

**Issue by rmey** [IBM-Bluemix/insurance-bot-dashboard#54]
I deployed the APP using a toolchain or manually. The Dashboard App is running bit only shows a text output with "Not Found" as content. No meaningful error in the log file.

**Comment by rmey** [comment]
The API endpoints working but not the webpage of Dashboard Microservice:
Try:
https://insurance-toolchain-2017-rm-4321-dashboard.mybluemix.net/chatlogs
https://insurance-toolchain-2017-rm-4321-dashboard.mybluemix.net/

**Comment by l2fprod** [comment]
The build shows:

```
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name " rimraf": name cannot contain leading or trailing spaces; name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pipeline/.npm/_logs/2017-07-17T07_43_34_336Z-debug.log

> insurance-bot-dashboard@0.1.0 deploy:prod /home/pipeline/123
> better-npm-run deploy:prod
```

Something we've seen in another demo, an issue with the latest npm.

**Comment by uwefassnacht** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/4811990e-3862-415d-b259-9b453e97247a "insurance-toolchain-eu"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/0a294ae0-5eaf-4e74-8fc0-d1531f5aa8ab "dashboard (master)") deployed [insurance-bot-dashboard](https://github.com/IBM-Bluemix/insurance-bot-dashboard/releases/tag/deploy-ibm-yp-eu-gb-uwe.fassnacht-de.ibm.com-cloudco-20170717-084751 "deploy-ibm-yp-eu-gb-uwe.fassnacht-de.ibm.com-cloudco-20170717-084751") to [cloudco](https://console.bluemix.net/apps/05c46b6b-250a-43c8-9c89-eed1121922d9?env_id=ibm:yp:eu-gb "ibm:yp:eu-gb:uwe.fassnacht@de.ibm.com:cloudco"), including commit ef04cba2e1cd98fc3eb9e826af10a796a01f6712
