### ISSUE TITLE
Deployment Tracker Service is discontinued

### ISSUE THREAD

**Issue by ptitzler** [IBM-Bluemix/insurance-bot-dashboard#56]
Please refer to the following document for details and migration instructions https://github.com/IBM-Bluemix/cf-deployment-tracker-client-node/wiki/migrating-to-the-new-metrics-tracker-client.

P.S. Your app is currently configured to require the latest version of the DTC for Node.js. This version no longer submits deployment tracking requests.

**Comment by uwefassnacht** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/4811990e-3862-415d-b259-9b453e97247a "insurance-toolchain-eu"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/0a294ae0-5eaf-4e74-8fc0-d1531f5aa8ab "dashboard (master)") deployed [insurance-bot-dashboard](https://github.com/IBM-Bluemix/insurance-bot-dashboard/releases/tag/deploy-ibm-yp-eu-gb-uwe.fassnacht-de.ibm.com-cloudco-20171208-095335 "deploy-ibm-yp-eu-gb-uwe.fassnacht-de.ibm.com-cloudco-20171208-095335") to [cloudco](https://console.bluemix.net/apps/6d73b7a2-9b81-42ea-a0fd-acf286ed0bb5?env_id=ibm:yp:eu-gb "ibm:yp:eu-gb:uwe.fassnacht@de.ibm.com:cloudco"), including commit bd442d94c1071479cea09468b6fed642e88cbe12

**Comment by ptitzler** [comment]
Thank you!
